name: Build docker image and push

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: izaw
            tag: izabelkaw/izaw

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ matrix.tag }}
          cache-from: |
            type=gha,scope=${{ matrix.name }}
            type=registry,ref=${{ matrix.tag }}
          cache-to: |
            type=gha,mode=max,scope=${{ matrix.name }}
